### ISSUE TITLE
Missing "a" and "client" tag on highlight event submit

### ISSUE THREAD

**Issue by leafes** [nostrband/nostr-site-content-cta#13]
Highlight event created through npub.pro context menu on the published website:

https://njump.me/nevent1qqsr7em4ffaqtfz0qd2de39kqnnshlneeehr5jgzg5a4w4jwh3vnzpspz4mhxue69uhhyetvv9ujuerpd46hxtnfduhsygxd3gsy5a6u9puk9w0th6she309kg8zgdzqhzpvthq7rny32wsdtypsgqqqye9q23xtlp

Highlight created through habla:

https://njump.me/nevent1qqsgn6fg24zpalz0s2g5eez0fc97qq7erv9marl5z8jxxz5ak8fa3mcpzpmhxue69uhkummnw3ezumt0d5hsygxd3gsy5a6u9puk9w0th6she309kg8zgdzqhzpvthq7rny32wsdtypsgqqqye9q9d5uaw

We need to add “a” and a “client” tag on highlight event submitted through context menu

**Comment by nostrband** [comment]
Fixed, updated on leafes47.npub.pro, will propagate to other sites during the day.

**Comment by leafes** [comment]
tested on leafes47.npub.pro
now highlights are submitted with an "a", and a "client" tags and displayed correctly on other clients 

<details><summary>Details</summary>
<p>

<img width="1912" alt="Screenshot 2024-11-05 at 20 00 21" src="https://github.com/user-attachments/assets/97930bdc-42e7-41a4-8c61-8e9926a87882">
<img width="1912" alt="Screenshot 2024-11-05 at 19 59 43" src="https://github.com/user-attachments/assets/a16b92a8-5504-475b-b866-4f94dab9dc27">
<img width="1912" alt="Screenshot 2024-11-05 at 19 57 34" src="https://github.com/user-attachments/assets/fc154b1c-0e21-474c-8451-9876fb131167">
<img width="1912" alt="Screenshot 2024-11-05 at 19 57 30" src="https://github.com/user-attachments/assets/1d210fe0-f8be-4fa8-a9f9-30d052d68de4">


</p>
</details>

**Comment by nostrband** [comment]
Yes looks good
