### ISSUE TITLE
[CTA] Bookmark button icon color doesn't adapt to accent color.

### ISSUE THREAD

**Issue by leafes** [nostrband/nostr-site-content-cta#18]
**Expected:** When user set CTA button to Bookmark and accent color is dark change icon color to white.
**Actual result:** 

<details><summary>DARK ACCENT: Icon is black, but should be white</summary>
<p>
<img width="1912" alt="Screenshot 2024-11-20 at 20 28 13" src="https://github.com/user-attachments/assets/f53248a2-ab08-4b82-88fa-67f1ecbe780c">

<img width="1912" alt="Screenshot 2024-11-20 at 20 27 28" src="https://github.com/user-attachments/assets/1c6e0559-3daa-4eea-8ff3-d4475728388a">
<img width="1912" alt="Screenshot 2024-11-20 at 20 27 11" src="https://github.com/user-attachments/assets/f7def605-8c7b-4e5b-80e9-a8cb917d0f46">

</p>
</details> 

<details><summary>BRIGHT ACCENT: Everything OK</summary>
<p>

<img width="913" alt="Screenshot 2024-11-20 at 20 30 52" src="https://github.com/user-attachments/assets/061967d3-6a61-42f3-8d3c-b97901fdbe14">
<img width="898" alt="Screenshot 2024-11-20 at 20 30 38" src="https://github.com/user-attachments/assets/6789d783-595a-4867-b81d-9733989daf5e">

</p>
</details>

**Comment by bekbolsun22** [comment]
ok, i will fix it
