### ISSUE TITLE
Zap is not showing up

### ISSUE THREAD

**Issue by leafes** [nostrband/nostr-site-content-cta#21]

**Comment by leafes** [comment]
hodlbod.npub.pro
![Image](https://github.com/user-attachments/assets/3a6d7cdf-3c7d-4cb4-88f4-753a1b6a6392)

**Comment by leafes** [comment]
currently investigating

**Comment by nostrband** [comment]
Haven't been able to replicate this, might be a temporary glitch with that zap

**Comment by leafes** [comment]
@nostrband wasn't able to replicate as well.
Any amount of zap is showed up correctly. Tested on different sites.

**Comment by nostrband** [comment]
Ok closing it.
