### ISSUE TITLE
Must take note address from np-content-cta attribute, not from meta-tags

### ISSUE THREAD

**Issue by nostrband** [nostrband/nostr-site-content-cta#22]
Ghost themes may display full posts on pages not dedicated to a post, and even many full-posts per page, and those won't have proper meta-tag.

**Comment by nostrband** [comment]
Check this: https://nvk-brugeman.npub.pro/

**Comment by nostrband** [comment]
Fixed content-cta 1.0.22 check on nvk-brugeman.npub.pro

**Comment by nostrband** [comment]
Shows likes/zaps, allows to post likes etc.

**Comment by leafes** [comment]
Likes, zaps, reactions, actions are shown and work correctly. Tested on desktop + mobile. Issue might be closed
